name: ipython-docker
version: '0.1.0.0'
author: Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
license: MIT
extra-source-files:
- ChangeLog.md
dependencies:
- base >=4.9 && <4.10
- language-dockerfile >=0.3.6.0
- zeromq4-haskell
- aeson
- bytestring
- unordered-containers
- text
- lifted-base
- aeson-qq
- lens-aeson
- convertible
- cryptonite
- time
- uuid
- mtl
- process
- monad-control
- lens
- ansi-terminal
- persistent
- persistent-sqlite
- haskeline
- stm
ghc-options: -threaded
executables:
  ipython-docker:
    main: Main.hs
    source-dirs: src
